#!/usr/bin/env python3
"""Build the resident 9px glyph cache used by runtime FLC subtitles."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import struct


HANGUL_BASE = 0xAC00
HANGUL_LAST = 0xD7A3
GLYPH_RECORD_BYTES = 32
VISIBLE_ROWS = 9
ENTRY_BYTES = 2 + (VISIBLE_ROWS * 2)
TEMPLATE_KEY_RE = re.compile(r"(?:^|;)key=(\d+)(?::|;|$)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the runtime FLC resident H9 glyph cache")
    parser.add_argument("translation", type=Path)
    parser.add_argument("font", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--template-key",
        action="append",
        type=int,
        required=True,
        help="include only this TEMPLATE.DAT key; repeat for one scene bundle",
    )
    args = parser.parse_args()

    overrides = json.loads(args.translation.read_text(encoding="utf-8"))
    if not isinstance(overrides, dict) or not overrides:
        raise ValueError("translation file must contain a non-empty ID-to-text object")
    selected = set(args.template_key)
    found: set[int] = set()
    matches: list[str] = []
    for entry_id, value in overrides.items():
        match = TEMPLATE_KEY_RE.search(entry_id)
        if match is None:
            continue
        key = int(match.group(1))
        if key in selected:
            found.add(key)
            matches.append(value)
    missing = sorted(selected - found)
    if missing:
        raise ValueError("missing TEMPLATE.DAT keys: " + ", ".join(map(str, missing)))
    if not matches:
        raise ValueError("selected TEMPLATE.DAT keys contain no translations")
    if any(not isinstance(value, str) for value in matches):
        raise ValueError("every translation value must be a string")

    syllable_indexes = sorted({
        ord(char) - HANGUL_BASE
        for value in matches
        for char in value
        if HANGUL_BASE <= ord(char) <= HANGUL_LAST
    })
    font = args.font.read_bytes()
    expected = (HANGUL_LAST - HANGUL_BASE + 1) * GLYPH_RECORD_BYTES
    if len(font) != expected:
        raise ValueError(f"unexpected H9 font size: {len(font)} != {expected}")

    lines = [
        "; Generated by tools/build_vision_h9_cache.py. Do not edit by hand.",
        f"VISION_H9_CACHE_COUNT equ {len(syllable_indexes)}",
        f"VISION_H9_CACHE_ENTRY_BYTES equ {ENTRY_BYTES}",
        "vision_h9_cache:",
    ]
    for index in syllable_indexes:
        start = index * GLYPH_RECORD_BYTES
        rows = struct.unpack_from("<9H", font, start)
        words = ", ".join([str(index), *(f"0x{row:04X}" for row in rows)])
        lines.append(f"    dw {words}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"entries: {len(syllable_indexes)}")
    print(f"resident bytes: {len(syllable_indexes) * ENTRY_BYTES}")
    print("template keys: " + ", ".join(map(str, sorted(selected))))
    print(f"output: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
