#!/usr/bin/env python3
"""Build page-aligned, scene-specific resident glyph caches for FLC subtitles."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import struct


HANGUL_BASE = 0xAC00
HANGUL_LAST = 0xD7A3
GLYPH_RECORD_BYTES = 32
VISIBLE_ROWS = 9
CACHE_ENTRY_BYTES = 2 + (VISIBLE_ROWS * 2)
EMS_PAGE_BYTES = 0x4000
MAX_CACHE_ENTRIES = 256
MAX_SUBTITLE_WIDTH = 320
TEMPLATE_KEY_RE = re.compile(r"(?:^|;)key=(\d+)(?::|;|$)")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="장면별 FLC 자막 HANGUL9 캐시 팩 빌드"
    )
    parser.add_argument("translation", type=Path)
    parser.add_argument("font", type=Path)
    parser.add_argument("pack_output", type=Path)
    parser.add_argument("include_output", type=Path)
    parser.add_argument("--ascii-font", type=Path, required=True)
    parser.add_argument(
        "--template-key",
        action="append",
        type=int,
        required=True,
        help="팩에 포함할 TEMPLATE.DAT 키; 장면마다 반복 지정",
    )
    args = parser.parse_args()

    overrides = json.loads(args.translation.read_text(encoding="utf-8"))
    if not isinstance(overrides, dict) or not overrides:
        raise ValueError("translation file must contain a non-empty ID-to-text object")

    requested = set(args.template_key)
    if len(requested) != len(args.template_key):
        raise ValueError("duplicate --template-key")
    texts: dict[int, str] = {}
    for entry_id, value in overrides.items():
        match = TEMPLATE_KEY_RE.search(entry_id)
        if match is None:
            continue
        key = int(match.group(1))
        if key not in requested:
            continue
        if key in texts:
            raise ValueError(f"duplicate TEMPLATE.DAT key: {key}")
        if not isinstance(value, str):
            raise ValueError(f"TEMPLATE.DAT key {key}: translation must be a string")
        texts[key] = value
    missing = sorted(requested - set(texts))
    if missing:
        raise ValueError("missing TEMPLATE.DAT keys: " + ", ".join(map(str, missing)))

    font = args.font.read_bytes()
    expected_font_bytes = (HANGUL_LAST - HANGUL_BASE + 1) * GLYPH_RECORD_BYTES
    if len(font) != expected_font_bytes:
        raise ValueError(f"unexpected H9 font size: {len(font)} != {expected_font_bytes}")
    ascii_font = args.ascii_font.read_bytes()
    if len(ascii_font) < 95 or ascii_font[0] != VISIBLE_ROWS:
        raise ValueError("--ascii-font must be Arena's 9px ARENAFNT.DAT")

    def line_width(line: str) -> int:
        width = 0
        for char in line.rstrip("&"):
            code = ord(char)
            if HANGUL_BASE <= code <= HANGUL_LAST:
                width += 10
            elif char == " ":
                width += ascii_font[1] + 1
            elif 0x21 <= code <= 0x7F:
                width += ascii_font[code - 0x20]
            elif char not in "\r\n":
                raise ValueError(f"unsupported subtitle character: {char!r}")
        return width

    pages: list[bytes] = []
    table: list[tuple[int, int]] = []
    widths: dict[int, int] = {}
    for key in sorted(texts):
        line_widths = [line_width(line) for line in texts[key].splitlines()]
        widest = max(line_widths, default=0)
        if widest > MAX_SUBTITLE_WIDTH:
            raise ValueError(
                f"TEMPLATE.DAT key {key}: {widest}px subtitle line exceeds "
                f"the {MAX_SUBTITLE_WIDTH}px FLC width"
            )
        widths[key] = widest
        indexes = sorted({
            ord(char) - HANGUL_BASE
            for char in texts[key]
            if HANGUL_BASE <= ord(char) <= HANGUL_LAST
        })
        if len(indexes) > MAX_CACHE_ENTRIES:
            raise ValueError(
                f"TEMPLATE.DAT key {key}: {len(indexes)} unique Hangul syllables "
                f"exceed the {MAX_CACHE_ENTRIES}-entry scene limit"
            )
        payload = bytearray()
        for index in indexes:
            start = index * GLYPH_RECORD_BYTES
            rows = struct.unpack_from("<9H", font, start)
            payload.extend(struct.pack("<H9H", index, *rows))
        if len(payload) > EMS_PAGE_BYTES:
            raise AssertionError((key, len(payload)))
        payload.extend(bytes(EMS_PAGE_BYTES - len(payload)))
        pages.append(bytes(payload))
        table.append((key, len(indexes)))

    args.pack_output.parent.mkdir(parents=True, exist_ok=True)
    args.pack_output.write_bytes(b"".join(pages))

    lines = [
        "; Generated by tools/build_cutscene_cache_pack.py. Do not edit by hand.",
        f"CUTSCENE_CACHE_PAGE_COUNT equ {len(table)}",
        f"CUTSCENE_CACHE_TABLE_COUNT equ {len(table)}",
        f"CUTSCENE_CACHE_MAX_ENTRIES equ {MAX_CACHE_ENTRIES}",
        f"VISION_H9_CACHE_ENTRY_BYTES equ {CACHE_ENTRY_BYTES}",
        "vision_h9_cache_count dw 0",
        "vision_h9_cache:",
        "    times CUTSCENE_CACHE_MAX_ENTRIES * VISION_H9_CACHE_ENTRY_BYTES db 0",
        "cutscene_cache_table:",
    ]
    for page_index, (key, count) in enumerate(table):
        lines.append(f"    dw {key}, FONT_EMS_PAGES + {page_index}, {count}")
    args.include_output.parent.mkdir(parents=True, exist_ok=True)
    args.include_output.write_text("\n".join(lines) + "\n", encoding="ascii")

    print(f"scenes: {len(table)}")
    print(f"EMS pages: {len(table)}")
    print(f"pack bytes: {len(pages) * EMS_PAGE_BYTES}")
    for key, count in table:
        print(
            f"key {key}: {count} entries, {count * CACHE_ENTRY_BYTES} bytes, "
            f"max line {widths[key]}px"
        )
    print(f"pack: {args.pack_output}")
    print(f"include: {args.include_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
